name: nucleosome
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - click=7.1.1
  - curl=7.68.0
  - cycler=0.10.0
  - dill=0.3.1.1
  - expat=2.2.6
  - freetype=2.10.1
  - hdf4=4.2.13
  - hdf5=1.10.5
  - intel-openmp=2020.0
  - jpeg=9c
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - libcurl=7.68.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libssh2=1.8.2
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - multiprocess=0.70.9
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1e
  - pandas=1.0.3
  - pathos=0.2.5
  - patsy=0.5.1
  - pip=20.0.2
  - pox=0.2.7
  - ppft=1.6.6.1
  - pyparsing=2.4.6
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2019.3
  - readline=8.0
  - scipy=1.4.1
  - seaborn=0.10.0
  - setuptools=46.1.1
  - six=1.14.0
  - sqlite=3.31.1
  - statsmodels=0.11.1
  - tk=8.6.10
  - tornado=6.0.4
  - vmd-python=3.0.6
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11

